config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/search', to: 'search#index'

  resources :products, only: :show, param: :asin
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @products = Amazon::Product.where("asin LIKE :search OR title LIKE :search", {search: "%#{params[:query]}%"})
    # Amazon Lookup if not found in the DB
    if @products.blank? && Amazon::Lookup::valid_ASIN(params[:query])
      code, product = Amazon::Lookup::ASIN(params[:query])
      if code == 200 # if found save, and return
        product.save!
        @products = [product]
      end
    end
  end
end

app/views/search/index.html.erb
<div class="ui raised segment">
  <h1 class="ui header"><%= params[:query] %> (<%= @products.count %> results)</h1>  
  <div class="ui divider"></div>
  <div class="ui divided link items">
    <% @products.each do |product| %>
      <a class="item" href="<%= product_path(product) %>">
        <div class="small image">
          <img src="<%= product_image(product) %>">
        </div>
        <div class="content">
          <div class="header"><%= product.title %></div>
          <div class="meta">
            <span><%= product.asin %></span>
          </div>
          <div class="description">
            <p><%= truncate product.category, length: 250 %></p>
          </div>
          <div class="extra">
            <div class="ui right floated primary button">
              View More
              <i class="right chevron icon"></i>
            </div>
            <div class="ui label"><i class="yellow star icon"></i> <%= product.ranking %> Ranking</div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>